# Generated by Django 4.1.2 on 2023-02-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='pic4',
        ),
        migrations.AddField(
            model_name='buyer',
            name='pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads'),
        ),
    ]
